### ISSUE TITLE
ht16k33_set_led    //hdev->buffer  

### ISSUE THREAD

**Issue by JHPaulKim** [samjkent/ht16k33-stm32-hal-driver#1]
Can you see an example of putting it in the buffer?

Can you give an example of how to set the address and message in 8 arrays.

uint16_t led, uint8_t value    --->  buffer .

**Comment by samjkent** [comment]
Here is an example where I've used it:
https://github.com/samjkent/stm32f4-midi-brain/blob/master/Src/main.c#L91

```
// Create an instance
HT16K33_HandleTypeDef led1;

// Set a single LED state
ht16k33_set_led(&led1, 0);

// Or alternatively, access buffer directly
led1->ht16k33_Buffer[0] = 0xFF;
// 8x16 byte arrays to store 128 LED states
led1->ht16k33_Buffer[7] = 0xFF;

// To update the physical display
ht16k33_write_display(&led1);
```

**Comment by JHPaulKim** [comment]
Thank you very much for you help very kind and detailed explanation.




2021년 3월 22일 (월) 오후 6:21, Sam Kent ***@***.***>님이 작성:

**Comment by samjkent** [comment]
No problem, I've added a README with an additional example
